/*
Copyright (C) 2017 Lars Hove Christiansen
http://virtcore.com

This file is a part of SQL Event Analyzer

	SQL Event Analyzer is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	SQL Event Analyzer is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with SQL Event Analyzer. If not, see <http://www.gnu.org/licenses/>.
*/

using System.Collections.Generic;

public static class Translator
{
	private static readonly Dictionary<string, string> _dictionary = new Dictionary<string, string>();

	public static void Clear()
	{
		_dictionary.Clear();
	}

	public static string GetText(string item)
	{
		return _dictionary[item];
	}

	public static void GenerateDictionary()
	{
		if (ConfigHandler.Language.ToLower() == "dansk")
		{
			_dictionary.Add("fileToolStripMenuItem", "&Filer");
			_dictionary.Add("toolsToolStripMenuItem", "Vær&ktøjer");
			_dictionary.Add("viewToolStripMenuItem", "&Vis");
			_dictionary.Add("helpToolStripMenuItem", "&Hjælp");
			_dictionary.Add("helpToolStripMenuItem1", "&Hjælp...");
			_dictionary.Add("changeConnectionToolStripMenuItem", "&Skift forbindelse...");
			_dictionary.Add("exitToolStripMenuItem", "&Afslut");
			_dictionary.Add("commandLineParametersToolStripMenuItem", "&Kommandolinieparametre...");
			_dictionary.Add("optionsToolStripMenuItem", "&Indstillinger...");
			_dictionary.Add("showHiddenColumnsToolStripMenuItem", "&Vis skjulte kolonner");
			_dictionary.Add("aboutToolStripMenuItem", "&Om...");
			_dictionary.Add("infoToolStripMenuItem", "&Info...");
			_dictionary.Add("okButton", "Ok");
			_dictionary.Add("newButton", "Ny");
			_dictionary.Add("cancelButton", "Annuller");
			_dictionary.Add("About", "Om");
			_dictionary.Add("Info", "Info");
			_dictionary.Add("Working", "Arbejder");
			_dictionary.Add("serverNameLabel", "Server navn:");
			_dictionary.Add("authenticationLabel", "Autentificering:");
			_dictionary.Add("usernameLabel", "Brugernavn:");
			_dictionary.Add("passwordLabel", "Password:");
			_dictionary.Add("usernameMissing", "Venligst angiv brugernavn.");
			_dictionary.Add("servernameMissing", "Venligst angiv servernavn.");
			_dictionary.Add("saveValuesCheckBox", "Gem værdier");
			_dictionary.Add("connectToSqlServerGroupBox", "Forbind til SQL Server");
			_dictionary.Add("backButton", "<- Tilbage");
			_dictionary.Add("nextButton", "Importer ->");
			_dictionary.Add("numberOfEventsLabel", "Antal hændelser:");
			_dictionary.Add("findToolStripButton", "Søg");
			_dictionary.Add("fontToolStripButton", "Font");
			_dictionary.Add("fontToolStripMenuItem", "&Font...");
			_dictionary.Add("formatToolStripMenuItem", "F&ormat");
			_dictionary.Add("toolStripMenuItemUndo", "Undo");
			_dictionary.Add("toolStripMenuItemRedo", "Redo");
			_dictionary.Add("toolStripMenuItemCut", "Klip");
			_dictionary.Add("toolStripMenuItemCopy", "Kopier");
			_dictionary.Add("toolStripMenuItemPaste", "Sæt ind");
			_dictionary.Add("toolStripMenuItemDelete", "Slet");
			_dictionary.Add("toolStripMenuItemSelectAll", "Marker alle");
			_dictionary.Add("toolStripMenuItemSelectAll1", "Marker alt");
			_dictionary.Add("exportToolStripButton1", "&Eksporter...");
			_dictionary.Add("SaveSessionAs", "Gem kollonesæt s&om...");
			_dictionary.Add("columnsToolStripButton", "Brugerdefinerede kolonner");
			_dictionary.Add("CustomColumn", "Brugerdefineret kolonne");
			_dictionary.Add("searchInTextData", "Søg i TextData");
			_dictionary.Add("fontsNotSupported", "Fonttyper i fed og kursiv er ikke supporteret.");
			_dictionary.Add("exportFileDialogFilterCsv", "Csv filer (*.csv)|*.csv|Alle filer (*.*)|*.*");
			_dictionary.Add("exportFileDialogFilterSql", "Sql filer (*.sql)|*.sql|Alle filer (*.*)|*.*");
			_dictionary.Add("exportFileDialogFilterPtt", "Xml filer (*.xml)|*.xml|Alle filer (*.*)|*.*");
			_dictionary.Add("Copy", "Kopier");
			_dictionary.Add("ErrorMessage", "Fejlbesked");
			_dictionary.Add("ErrorOccured", "Fejl");
			_dictionary.Add("exit", "Afslut");
			_dictionary.Add("and", "og");
			_dictionary.Add("or", "eller");
			_dictionary.Add("readsLabel", "Reads mellem");
			_dictionary.Add("writesLabel", "Writes mellem");
			_dictionary.Add("cpuLabel", "CPU mellem");
			_dictionary.Add("rowsLabel", "Rows mellem");
			_dictionary.Add("durationLabel", "Duration mellem");
			_dictionary.Add("spidLabel", "SPID mellem");
			_dictionary.Add("idLabel", "Id mellem");
			_dictionary.Add("resetButton", "Nulstil");
			_dictionary.Add("activateButton", "Aktiver");
			_dictionary.Add("deactivateButton", "Deaktiver");
			_dictionary.Add("startTimeLabel", "StartTime mellem");
			_dictionary.Add("firstId", "Første Id");
			_dictionary.Add("secondId", "Sidste Id");
			_dictionary.Add("firstSPID", "Første SPID");
			_dictionary.Add("secondSPID", "Sidste SPID");
			_dictionary.Add("firstDuration", "Første Duration");
			_dictionary.Add("secondDuration", "Sidste Duration");
			_dictionary.Add("firstStartTime", "Første StartTime");
			_dictionary.Add("secondStartTime", "Sidste StartTime");
			_dictionary.Add("firstReads", "Første Reads");
			_dictionary.Add("secondReads", "Sidste Reads");
			_dictionary.Add("firstWrites", "Første Writes");
			_dictionary.Add("secondWrites", "Sidste Writes");
			_dictionary.Add("firstCpu", "Første CPU");
			_dictionary.Add("secondCpu", "Sidste CPU");
			_dictionary.Add("firstRows", "Første Rows");
			_dictionary.Add("secondRows", "Sidste Rows");
			_dictionary.Add("removeButton", "Fjern");
			_dictionary.Add("addButton", "Tilføj");
			_dictionary.Add("whereColumnLabel", "Hvor kolonne");
			_dictionary.Add("showHiddenCheckBox", "Vis skjulte");
			_dictionary.Add("All", "Vælg...");
			_dictionary.Add("None", "Ingen");
			_dictionary.Add("FetchingData", "Henter data...");
			_dictionary.Add("nameLabel", "Navn:");
			_dictionary.Add("Type", "Type:");
			_dictionary.Add("Output", "Output");
			_dictionary.Add("Input", "Input");
			_dictionary.Add("hiddenCheckBox", "Skjult");
			_dictionary.Add("shown", "Vist");
			_dictionary.Add("enabledCheckBox", "Aktiveret");
			_dictionary.Add("inactive", "Deaktiveret");
			_dictionary.Add("change", "Skift");
			_dictionary.Add("toggleHidden", "Skift skjult");
			_dictionary.Add("toggleActive", "Skift aktiveret");
			_dictionary.Add("uniqueColumn", "En anden kolonne med det samme navn eksisterer allerede.\r\n\r\nKolonnenavne skal være unikke.");
			_dictionary.Add("emptyName", "\"Navn\" skal udfyldes.");
			_dictionary.Add("invalidName", "\"Navn\" ikke gyldigt.");
			_dictionary.Add("emptyInput", "Input skal udfyldes.");
			_dictionary.Add("emptyOutput", "Output skal udfyldes.");
			_dictionary.Add("inputLength", "Input længde er mere end 4000 karakterer.\r\nMaksimal tilladt længde er 4000 karakterer.");
			_dictionary.Add("outputLength", "Output længde er mere end 4000 karakterer.\r\nMaksimal tilladt længde er 4000 karakterer.");
			_dictionary.Add("saveChanges", "Gem ændringer?");
			_dictionary.Add("preparingCustomColumns", "Forbereder brugerdefineret kolonne");
			_dictionary.Add("handlingCustomColumnData", "Håndterer brugerdefineret kolonnedata");
			_dictionary.Add("handlingCustomColumns", "Håndterer brugerdefinerede kolonner");
			_dictionary.Add("creatingIndexes", "Opretter indeks...");
			_dictionary.Add("fileLabel", "Fil:");
			_dictionary.Add("sessionLabel", "Session:");
			_dictionary.Add("sizeLabel", "Størrelse:");
			_dictionary.Add("statusLabel", "Status:");
			_dictionary.Add("parsingTraceFiles", "Analyserer tracedata");
			_dictionary.Add("parsingSessions", "Analyserer sessioner");
			_dictionary.Add("importingFiles", "Importerer fil(er)...");
			_dictionary.Add("importingSessions", "Importerer session(er)...");
			_dictionary.Add("populatingFullText", "Populerer fulltext katalog");
			_dictionary.Add("Columns", "Kolonner");
			_dictionary.Add("Name", "Navn");
			_dictionary.Add("editButton", "Rediger");
			_dictionary.Add("moveDownButton", "Flyt ned");
			_dictionary.Add("moveUpButton", "Flyt op");
			_dictionary.Add("createButton", "Opret");
			_dictionary.Add("importToolStripMenuItem", "&Åbn kolonnesæt...");
			_dictionary.Add("saveToolStripMenuItem", "&Gem kolonnesæt");
			_dictionary.Add("recentFilesToolStripMenuItem", "Seneste file&r");
			_dictionary.Add("closeToolStripMenuItem", "&Luk");
			_dictionary.Add("actionToolStripMenuItem", "&Handling");
			_dictionary.Add("deleteAllMenuItem1", "Slet &alle");
			_dictionary.Add("xmlFilter", "Xml filer|*.xml|Alle filer|*.*");
			_dictionary.Add("fileNotFound", "Kolonnesæt fil \"{0}\" blev ikke fundet.");
			_dictionary.Add("postScriptFileNotFound", "Post script filen blev ikke fundet.");
			_dictionary.Add("deleteColumns", "Slet de markerede kolonner?");
			_dictionary.Add("couldNotPaste", "Kan ikke indsætte kolonner da længden på en eller flere kolonnenavne er mere end de tilladte 120 karakterer.");
			_dictionary.Add("copy1", "kopi");
			_dictionary.Add("FindNext", "Find næste");
			_dictionary.Add("searchForLabel", "Søg efter:");
			_dictionary.Add("matchCaseCheckBox", "Match store/små bogstaver");
			_dictionary.Add("matchWholeWordCheckBox", "Match kun hele ord");
			_dictionary.Add("wrapAroundCheckBox", "Søg i hele teksten");
			_dictionary.Add("showNoMoreMatchesMessageCheckBox", "Vis \"Ikke flere resultater.\"");
			_dictionary.Add("directionGroupBox", "Retning");
			_dictionary.Add("down", "Ned");
			_dictionary.Add("up", "Op");
			_dictionary.Add("useRegExCheckBox", "Brug RegEx");
			_dictionary.Add("optionsGroupBox", "Valg");
			_dictionary.Add("searchGroupBox", "Søg");
			_dictionary.Add("NotFound", "Ikke fundet.");
			_dictionary.Add("NoMoreMatches", "Ikke flere resultater.");
			_dictionary.Add("layoutGroupBox", "Layout");
			_dictionary.Add("itemsPerPageLabel", "Antal poster per side");
			_dictionary.Add("otherGroupBox", "Program");
			_dictionary.Add("languageLabel", "Sprog");
			_dictionary.Add("Settings", "Indstillinger");
			_dictionary.Add("ItemsPerPageZero", "Antal poster per side skal være større end 0.");
			_dictionary.Add("ItemsPerPageInvalid", "Antal poster per side er ikke et gyldigt tal.");
			_dictionary.Add("traceFileCountLabel", "Antal tracefiler:");
			_dictionary.Add("sessionCountLabel", "Antal sessioner:");
			_dictionary.Add("traceFilesGroupBox", "Importer tracefiler");
			_dictionary.Add("sessionsGroupBox", "Importer sessioner");
			_dictionary.Add("fileNameColumnHeader", "Filnavn");
			_dictionary.Add("sessionIdColumnHeader", "Session Id");
			_dictionary.Add("sizeColumnHeader", "Størrelse (KB)");
			_dictionary.Add("dateCreatedColumnHeader", "Oprettelsesdato");
			_dictionary.Add("traceFileDirectoryGroupBox", "Import sti");
			_dictionary.Add("loadButton", "Hent");
			_dictionary.Add("traceFileSecurityInfo", "Tracefil sti eksisterer ikke.\r\n\r\nHvis du læser fra en anden maskine end SQL Serveren, benyt da en UNC sti, og tjek at serveren og SQL Server service kontoen har læserettigheder til den delte netværkssti.");
			_dictionary.Add("ClearButtonText", "Nulstil");
			_dictionary.Add("SearchButtonText", "Søg");
			_dictionary.Add("PageText", "Side");
			_dictionary.Add("IsDataModifiedText", "Data er ændret siden sidste visning. Data vil blive hentet på ny.");
			_dictionary.Add("IsDataModifiedCaptionText", "Data er ændret");
			_dictionary.Add("OutOf", "ud af");
			_dictionary.Add("TotalText", "Total");
			_dictionary.Add("SearchBoxToolTipText", "Brug * som wildcard");
			_dictionary.Add("SearchBoxListToolTipText", "Brug komma til at separere værdier, f.eks. 123,456,789");
			_dictionary.Add("ImportFileMissing", "Kolonne importfil mangler en eller flere elementer.");
			_dictionary.Add("SqlServerNotSupported", "SQL Server version er ikke supporteret.");
			_dictionary.Add("Close", "Luk");
			_dictionary.Add("infoText", "Applikation version: \t\t{0}\r\nSQL Server version: \t{1}\r\nSQL Server: \t\t{2}\r\nSession Id: \t\t{3}\r\nSidste importtid: \t\t{4}\r\nSidste kolonnehåndteringstid: \t{5}\r\nSidste datahentningstid: \t{6}");
			_dictionary.Add("GreaterThanZeroEqual", "\"{0}\" skal være større end eller lig med 0.");
			_dictionary.Add("GreaterThanMinusOneEqual", "\"{0}\" skal være større end eller lig med -1.");
			_dictionary.Add("GreaterThanZero", "\"{0}\" skal være større end 0.");
			_dictionary.Add("NotValidNumber", "\"{0}\" er ikke et gyldigt tal.");
			_dictionary.Add("ErrorRegistry", "Kan ikke gemme værdi i registreringsdatabasen.\r\n\r\n{0}");
			_dictionary.Add("ErrorDeletingRegistry", "Kan ikke slette værdi fra registreringsdatabasen.\r\n\r\n{0}");
			_dictionary.Add("ResetLayout", "Nulstil layout");
			_dictionary.Add("preparing", "Forbereder...");
			_dictionary.Add("customColumnsToolStripMenuItem", "&Brugerdefinerede kolonner...");
			_dictionary.Add("clrEnabled", "CLR understøttelse er ikke aktiveret på SQL Serveren.\r\n\r\nFor at alle funktioner er tilgængelige, skal CLR understøttelse aktiveres.");
			_dictionary.Add("equal", "Lig med");
			_dictionary.Add("notEqual", "Forskellig fra");
			_dictionary.Add("in", "Findes i");
			_dictionary.Add("notin", "Ikke findes i");
			_dictionary.Add("greaterThan", "Større end");
			_dictionary.Add("lessThan", "Mindre end");
			_dictionary.Add("findToolStripMenuItem", "Søg...");
			_dictionary.Add("dataAndFiltersGroupBox", "Data og filtre");
			_dictionary.Add("eventsGroupBox", "Hændelser");
			_dictionary.Add("errorInCustomColumn", "Fejl i brugerdefineret kolonne");
			_dictionary.Add("sortAlphabeticallyCheckBox", "Sorter navn alfabetisk");
			_dictionary.Add("filter1GroupBox", "Filter 1 (for standard kolonner)");
			_dictionary.Add("filter2GroupBox", "Filter 2 (for brugerdefinerede kolonner)");
			_dictionary.Add("standardColumnsToolStripMenuItem", "Standard kolonner");
			_dictionary.Add("searchInGroupBox", "Søg i");
			_dictionary.Add("preparingLabel", "Forbereder...");
			_dictionary.Add("enableCLRButton", "Aktiver CLR understøttelse");
			_dictionary.Add("noRegExButton", "Fortsæt uden CLR understøttelse");
			_dictionary.Add("clrNotAvailable", "CLR understøttelse er ikke aktiveret");
			_dictionary.Add("RegEx", "RegEx");
			_dictionary.Add("SQL", "SQL");
			_dictionary.Add("Constant", "Konstant");
			_dictionary.Add("StoredProcedureName", "Stored Procedure navn");
			_dictionary.Add("StoredProcedureParameter", "Stored Procedure parameter");
			_dictionary.Add("LogParameter", "Log parameter");
			_dictionary.Add("Export", "Eksporter");
			_dictionary.Add("Options", "Valg");
			_dictionary.Add("Format", "Format");
			_dictionary.Add("allPagesRadioButton", "Alle sider");
			_dictionary.Add("currentPageRadioButton", "Nuværende side");
			_dictionary.Add("traceFileGroupBox", "Tracing (til optagelse)");
			_dictionary.Add("traceFileInfoLinkLabel", "Hvis du skriver fra en anden maskine end SQL Serveren, benyt da en UNC sti, og tjek at serveren og SQL Server service kontoen har skriverettigheder til den delte netværkssti.");
			_dictionary.Add("traceFileDirLabel", "Tracefil sti");
			_dictionary.Add("tracingFunctionalityLabel", "Tracing funktionalitet");
			_dictionary.Add("traceDirEmpty", "Tracefil sti skal udfyldes.");
			_dictionary.Add("recordToolStripMenuItem", "&Optag...");
			_dictionary.Add("Record", "Optag");
			_dictionary.Add("StatusIdle", "Status: Inaktiv");
			_dictionary.Add("startButton", "Start");
			_dictionary.Add("pauseButton", "Pause");
			_dictionary.Add("stopButton", "Stop");
			_dictionary.Add("traceRights", "Ikke nok rettigheder til tracefil sti.\r\n\r\nHvis du forbinder til en ikke-lokal SQL Server, benyt da en UNC sti, og tjek at serveren og SQL Server service kontoen har skriverettigheder til den delte netværkssti.\r\n\r\nTracefil sti kan sættes i menuen \"Indstillinger\".");
			_dictionary.Add("outOfMemory", "Ikke nok hukommelse.");
			_dictionary.Add("statusRecording", "Status: Optager...");
			_dictionary.Add("statusPaused", "Status: Pause");
			_dictionary.Add("continueButton", "    Fortsæt");
			_dictionary.Add("abortRecording", "Optagelse er i gang.\r\n\r\nAfbryd optagelse?");
			_dictionary.Add("errorDeletingTrace", "Fejl ved sletning af tracefil.\r\n\r\n{0}");
			_dictionary.Add("errorCompressingTrace", "Fejl ved komprimering af tracefil.\r\n\r\n{0}");
			_dictionary.Add("errorDeletingSession", "Fejl ved sletning af session.\r\n\r\n{0}");
			_dictionary.Add("createTraceDirManually", "Tracefil stien \"{0}\" eksisterer ikke.\r\n\r\nStien skal oprettes manuelt.");
			_dictionary.Add("unattended", "SQLEventAnalyzer.exe [\r\n                    [\r\n                     (-p:\"Post script fil\")\r\n                     (-e:\"Post script\")\r\n                     (-z:\"Antal filer\")\r\n                     (-d)\r\n                     (-g:\"Statistiknavne\" (-f1:\"Filter 1 navne\") (-f2:\"Filter 2 navne\") [(-sp:\"Sti\") eller (-sw:\"Statistiknavne\")])\r\n                     [\r\n                      [\r\n                       [\r\n                        [-n:Antal tracefiler] eller [-f:\"Tracefilnavn\"]\r\n                       ]\r\n                       (-s:\"Session Id\" (-x))\r\n                      ]\r\n\r\n                      eller\r\n\r\n                      [-i:\"Session Id\" (-x)]\r\n                     ]\r\n                     [-l:\"Import sti\"]\r\n                    ]\r\n\r\n                    eller\r\n\r\n                    [-u:\"Session Id\" (-v (-a:\"Applikationsnavn\")) (-x)]\r\n\r\n                    eller\r\n\r\n                    [-r]\r\n                   ]\r\n                   (-c:\"Brugerdefineret kolonnesæt filnavn\")\r\n                   (-t:\"SQL Server Connection String\" (-ms:\"SQL\"))\r\n                   (-o)\r\n                   (-w:\"Web service\")\r\n                   (-b:\"Databasenavn\")\r\n                   (-m:\"Tekst\")\r\n\r\n[]: Obligatorisk parameter\r\n(): Valgfri parameter\r\n\r\nParametre:\r\n    (-p:\"Post script fil\"):\r\n     Fuld sti til SQL script fil.\r\n     Scriptet vil blive eksekveret efter import af tracefiler.\r\n\r\n    (-e:\"Post script\"):\r\n     SQL script.\r\n     Scriptet vil blive eksekveret efter import af tracefiler.\r\n\r\n    (-z:\"Antal filer\"):\r\n     Komprimer tracefiler efter import. De seneste \"Antal filer\" vil blive beholdt og resten vil blive slettet.\r\n     Brug 0 for at beholde alle filer.\r\n\r\n    (-d):\r\n     Slet tracefiler efter import.\r\n\r\n    [-n:Antal tracefiler]:\r\n     Importerer de N nyeste tracefiler.\r\n     Brug 0 for at importere alle tracefiler.\r\n\r\n    [-f:\"Tracefilnavn\"]:\r\n     Importerer alle tracefiler nyere end den angivne tracefil.\r\n     Hændelserne i den angivne tracefil vil ikke blive importeret.\r\n\r\n    (-s:\"Session Id\"):\r\n     Tilføj hændelser til den angivne session.\r\n\r\n     Hvis -s er angivet, vil hændelser blive tilføjet til den angivne session.\r\n     Hvis -s ikke er angivet, vil hændelser blive importeret til en ny session.\r\n\r\n    [-i:\"Session Id\"]:\r\n     Importerer alle tracefiler nyere end den sidst importerede tracefil fundet i\r\n     \"FileName\" kolonnen i TraceData tabellen for den angivne session.\r\n\r\n     Hvis -i er angivet, vil hændelser blive tilføjet til den angivne session.\r\n\r\n    [-l:\"Import sti\"]:\r\n     Sti til tracefiler, som skal importeres.\r\n\r\n    [-u:\"Session Id\"]:\r\n     Benyt den angivne session ved start.\r\n\r\n    (-v):\r\n     Deaktiver mulighed for at ændre data i TraceData tabellen.\r\n\r\n    (-a:\"Applikationsnavn\"):\r\n     Benyt angivet applikationsnavn i stedet for \"SQL Event Analyzer\".\r\n\r\n    (-b:\"Databasenavn\"):\r\n     Benyt angivet databasenavn i stedet for \"SQLEventAnalyzer\".\r\n\r\n    (-m:\"Tekst\"):\r\n     Tilføj angivet tekst til log for kørsel.\r\n\r\n    (-ms:\"SQL\"):\r\n     Tilføj output fra angivet SQL til log for kørsel. Output returneres fra første række i kolonnen \"Message\".\r\n     -t parameteren angiver den benyttede SQL Server forbindelse.\r\n\r\n    (-x):\r\n     Gennemtving sletning af TraceData tabellen for den angivne session ved afslutning.\r\n\r\n    [-r]:\r\n     Start i optagetilstand.\r\n\r\n    (-c:\"Brugerdefineret kolonnesæt filnavn\"):\r\n     Fuld sti til fil, som skal benyttes som brugerdefineret kolonnesæt.\r\n\r\n    (-t:\"SQL Server Connection String\"):\r\n     Forbind ved brug af den angivne SQL Server Connection String.\r\n     Hvis et password benyttes i den angivne SQL Server Connection String, skal det være krypteret.\r\n     Hvis -t ikke er angivet, vil den sidst succesfulde forbindelse blive benyttet.\r\n\r\n    (-o):\r\n     Log for kørsel gemmes i eksekveringssti.\r\n\r\n    (-w:\"Web service\"):\r\n     Send log for kørsel til den angivne web service.\r\n\r\n    (-g:\"Statistiknavne\"):\r\n     Generer statistik udfra de gemte statistikker med de angivne navne.\r\n     Navne kan adskilles med komma.\r\n\r\n    (-f1:\"Filter 1 navne\"):\r\n     Aktiver Filter 1 med de angivne navne til brug for generering af statistik.\r\n     Navne kan adskilles med komma.\r\n\r\n    (-f2:\"Filter 2 navne\"):\r\n     Aktiver Filter 2 med de angivne navne til brug for generering af statistik.\r\n     Navne kan adskilles med komma.\r\n\r\n    (-sw:\"Statistiknavne\"):\r\n     Kræver at -w er angivet. Sender genereret statistik med de angivne navne til den angivne web service.\r\n     De angivne navne skal skal være repræsenteret i navnene fra -g parameteren.\r\n\r\n    (-sp:\"Sti\")\r\n     Gemmer genereret statistik i den angivne sti.\r\n\r\nEksempel 1 (importer de to nyeste tracefiler og kør script bagefter):\r\nSQLEventAnalyzer.exe -p:\"C:\\SomeDir\\PostScript.sql\" -n:2 -l:\"C:\\TraceFiles\"\r\n\r\nEksempel 2 (importer alle tracefiler nyere end \"LastImported.trc\"):\r\nSQLEventAnalyzer.exe -f:\"C:\\SomeDir\\LastImported.trc\" -l:\"C:\\TraceFiles\"\r\n\r\nEksempel 3 (importer alle tracefiler nyere end den sidst importerede tracefil fundet i\r\n\"FileName\" kolonnen i TraceData tabellen og tilføj hændelserne til en eksisterende session):\r\nSQLEventAnalyzer.exe -i:\"collect\" -l:\"C:\\TraceFiles\"");
			_dictionary.Add("markSelectedAndContinueToolStripMenuItemAppend", "Importer markerede (tilføj til nuværende session)");
			_dictionary.Add("markSelectedAndContinueToolStripMenuItemDelete", "Importer markerede (slet nuværende session)");
			_dictionary.Add("importCheckedToolStripMenuItemAppend", "Importer afkrydsede (tilføj til nuværende session)");
			_dictionary.Add("importCheckedToolStripMenuItemDelete", "Importer afkrydsede (slet nuværende session)");
			_dictionary.Add("cmdTitle", "Kommandolinieparametre");
			_dictionary.Add("handlingPostScript", "Håndterer post script...");
			_dictionary.Add("helpFileNotFound", "Hjælpefil blev ikke fundet.");
			_dictionary.Add("viewToolStripMenuItem1", "Vis...");
			_dictionary.Add("searchInInput", "Søg i input");
			_dictionary.Add("searchInOutput", "Søg i output");
			_dictionary.Add("statisticsTabPage", "Statistik");
			_dictionary.Add("groupBy", "Grupper efter");
			_dictionary.Add("View", "Vis");
			_dictionary.Add("ExportSuccessful", "Eksport succesfuld.");
			_dictionary.Add("ExportFailed", "Eksport fejlede.");
			_dictionary.Add("filter1Active", "Filter 1: Aktiv");
			_dictionary.Add("filter1NotActive", "Filter 1: Ikke aktiv");
			_dictionary.Add("filter2Active", "Filter 2: Aktiv");
			_dictionary.Add("filter2NotActive", "Filter 2: Ikke aktiv");
			_dictionary.Add("Enabled", "Aktiv");
			_dictionary.Add("newFonts", "Nye fonte, der er tilføjet til Windows mens {0} kører, kan ikke blive tilføjet på grund af en fejl i Windows.\r\n\r\nFor at tilføje fonten, genstart {0}.");
			_dictionary.Add("Timeline", "&Tidslinie...");
			_dictionary.Add("DataMouse", "Data (Flyt musen over en række for at se data)");
			_dictionary.Add("relativeStartTimeLabel", "StartTime relativ til første hændelse:");
			_dictionary.Add("MaxRows", "Kan ikke vise tidslinie.\r\nAntal hændelser overstiger de tilladte {0}.\r\n\r\nTilpas antallet af hændelser ved brug af filter 1 og filter 2.");
			_dictionary.Add("MaxDays", "Kan ikke vise tidslinie.\r\nTidsintervallet i de valgte hændelser kan ikke være mere end 1 dag.\r\n\r\nTilpas antallet af hændelser ved brug af filter 1 og filter 2.");
			_dictionary.Add("fitToScreenToolStripMenuItem", "&Tilpas til vindue");
			_dictionary.Add("Save", "&Gem...");
			_dictionary.Add("barLabelsLabel", "Baretiket:");
			_dictionary.Add("viewBarLabelsToolStripMenuItem", "&Vis baretiketter");
			_dictionary.Add("NotValidIntegerText", "er ikke et gyldigt tal");
			_dictionary.Add("Parameters", "Parametre");
			_dictionary.Add("NameColumn", "Navn");
			_dictionary.Add("ValueColumn", "Værdi");
			_dictionary.Add("insertParameter", "Indsæt parameter");
			_dictionary.Add("EnterParameterValue", "Udfyld parameterværdi");
			_dictionary.Add("Parameter", "Parameter");
			_dictionary.Add("valueLabel", "Værdi:");
			_dictionary.Add("ValueMissing", "Værdi skal udfyldes.");
			_dictionary.Add("ParameterNamesNotUnique", "Kan ikke fortsætte når parameternavne ikke er unikke.");
			_dictionary.Add("Refresh", "Opdater");
			_dictionary.Add("paramInfo", "Parameterværdier kan gemmes permanent i indstillingerne for brugerdefinerede kolonner.");
			_dictionary.Add("DeleteSelected", "Slet valgte");
			_dictionary.Add("deleteParameters", "Slet valgte parametre?");
			_dictionary.Add("NewSession", "&Nyt kollonesæt");
			_dictionary.Add("CreateNewSession", "Opret nyt kollonesæt?");
			_dictionary.Add("Width", "Bredde:");
			_dictionary.Add("emptyWidth", "\"Bredde\" skal udfyldes.");
			_dictionary.Add("widthNotValidNumber", "Værdi for \"Bredde\" er ikke et gyldigt tal.");
			_dictionary.Add("widthBetween", "Værdi for \"Bredde\" skal være mellem 20 og 1000.");
			_dictionary.Add("sessionreserved", "\"{SessionId}\" er et reserveret navn og kan ikke benyttes.");
			_dictionary.Add("traceFilesTabPage", "Vis tracefiler");
			_dictionary.Add("sessionsTabPage", "Vis sessioner");
			_dictionary.Add("sessionsInfoGroupBox", "Benyt session");
			_dictionary.Add("CurrentText", "Nuværende");
			_dictionary.Add("ActiveText", "Aktiv");
			_dictionary.Add("OverTakeSession", "Den valgte session er aktiv i en anden instans af {0}.\r\nBenyt session?");
			_dictionary.Add("useSessionToolStripMenuItem", "Benyt session");
			_dictionary.Add("loadColumnSetToolStripMenuItem", "&Hent kolonnesæt");
			_dictionary.Add("closeCCWindow", "\"Brugerdefinerede kolonner\" vinduet skal lukkes før der kan fortsættes.");
			_dictionary.Add("checkingImportDirectory", "Checker import sti...");
			_dictionary.Add("keepSessionLabel", "Behold session ved afslutning");
			_dictionary.Add("deleteSelectedToolStripMenuItem", "Slet valgte");
			_dictionary.Add("DeleteSelectedTraceFiles", "Slet valgte tracefiler?");
			_dictionary.Add("DeleteSelectedSessions", "Slet valgte sessioner?");
			_dictionary.Add("ViewTextData", "Vis TextData...");
			_dictionary.Add("CopyToClipboard", "Kopier navn til udklipsholder");
			_dictionary.Add("EnableFileNameAndType", "Aktiver \"FileName\" og \"Type\"");
			_dictionary.Add("RestartRequired", "Applikationen skal genstartes før ændringerne træder i kraft.\r\n\r\nApplikationen vil nu afslutte.");
			_dictionary.Add("ImportSameAgain", "Importer de samme valgte igen");
			_dictionary.Add("deleteToolStripButton", "Slet");
			_dictionary.Add("saveToolStripButton", "Gem som...");
			_dictionary.Add("defaultToolStripButton", "Marker valgte som standard");
			_dictionary.Add("Empty", "Tom");
			_dictionary.Add("SavedSearch", "Søgning");
			_dictionary.Add("SavedSearchName", "Navn på søgning");
			_dictionary.Add("Name1", "Navn:");
			_dictionary.Add("NameNotValid", "Navn er ikke gyldigt.");
			_dictionary.Add("DeleteSearch", "Slet søgning \"{0}\"?");
			_dictionary.Add("SaveSearch", "Erstat søgning \"{0}\"?");
			_dictionary.Add("Yes", "Ja");
			_dictionary.Add("No", "Nej");
			_dictionary.Add("NoRowsToDisplay", "Der er ingen handlinger at vise.");
			_dictionary.Add("SelectAll", "Vælg alle");
			_dictionary.Add("Rename", "Omdøb");
			_dictionary.Add("NewName", "Nyt navn");
			_dictionary.Add("TraceFile", "Tracefil");
			_dictionary.Add("Session", "Session");
			_dictionary.Add("NameMustBeUnique", "Navne skal være unikke.");
			_dictionary.Add("NotClosedParanthes", "Ikke alle paranteser er afsluttet.");
			_dictionary.Add("TextDataCleaned", "Renset TextData");
			_dictionary.Add("NewSession2", "Opret ny session");
			_dictionary.Add("databaseNameLabel", "Database navn:");
			_dictionary.Add("DatabaseNameMissing", "Database navn mangler.");
			_dictionary.Add("sessionNameLabel", "Session navn:");
			_dictionary.Add("SessionNameMissing", "Session navn mangler.");
			_dictionary.Add("CheckingAccessRights", "Tjekker rettigheder...");
			_dictionary.Add("PermanentlyDeleteSession", "Du har manuelt oprettet eller forbundet til sessionen \"{0}\". Det er valgt ikke at beholde sessioner ved afslutning (kan konfigureres i Indstillinger).\r\n\r\nSkal sessionen \"{0}\" slettes permanent?");
			_dictionary.Add("Initializing", "Initialiserer...");
			_dictionary.Add("CheckForUpdates", "&Check for opdateringer...");
			_dictionary.Add("Changelog", "Ændringslog");
			_dictionary.Add("CheckForUpdatesTitle", "Check for opdateringer");
			_dictionary.Add("checkOnStartCheckBox", "Check for opdateringer ved start");
			_dictionary.Add("updateButtonUpdate", "Opdater");
			_dictionary.Add("updateButtonCheck", "Check");
			_dictionary.Add("updateButtonChecking", "Checker...");
			_dictionary.Add("updateButtonDownloading", "Henter...");
			_dictionary.Add("updateButtonDownloaded", "Hentet");
			_dictionary.Add("currentVersionText", "Nuværende version");
			_dictionary.Add("NoUpdateServer", "Kan ikke kontakte opdateringsserver.");
			_dictionary.Add("newVersionText", "Ny version {0} tilgængelig.");
			_dictionary.Add("LatestVersionInstalled", "Seneste version er allerede installeret.");
			_dictionary.Add("errorDownloading", "Fejl ved hentning af opdatering.");
			_dictionary.Add("DeleteThisValue", "Slet");
			_dictionary.Add("DeleteSavedValue", "Slet det gemte password?");
			_dictionary.Add("AutoPopulateFilter2", "Automatisk udfyld Filter 2 dropdown værdier");
			_dictionary.Add("ReloadValuesCheckBoxToolTip", "Automatisk udfyld dropdown værdier");
			_dictionary.Add("generateEncryptedPasswordToolStripMenuItem", "&Generer krypteret password...");
			_dictionary.Add("encryptPassword", "Krypter password");
			_dictionary.Add("passwordGroupBox", "Password");
			_dictionary.Add("passwordInfo", "Se kommandolinieparametre for brug af krypteret password.");
			_dictionary.Add("decryptedLabel", "Dekrypteret:");
			_dictionary.Add("encryptedLabel", "Krypteret:");
			_dictionary.Add("onlineToolStripMenuItem", "&Abonnement");
			_dictionary.Add("settingsToolStripMenuItem", "&Indstillinger...");
			_dictionary.Add("OnlineSettingsTitle", "Abonnement indstillinger");
			_dictionary.Add("OnlineUpdateInfo", "Hvis aktiveret, vil der ved programstart tjekkes for opdaterede brugerdefinerede kolonner. Hvis nye brugerdefinerede kolonner er fundet, vil de automatisk blive opdateret, og eksisterende brugerdefinerede kolonner vil blive overskrevet.");
			_dictionary.Add("OnlineEnableAutoUpdate", "Aktiver automatisk opdatering");
			_dictionary.Add("OnlineUpdateServerLabel", "Opdateringsserver:");
			_dictionary.Add("OnlineFileNameLabel", "Filnavn:");
			_dictionary.Add("OnlineFileVersionLabel", "Filversion:");
			_dictionary.Add("MissingUpdateServer", "Opdateringsserver skal udfyldes.");
			_dictionary.Add("OnlineAutomaticUpdate", "Abonnement");
			_dictionary.Add("restartToUpdateLabel", "Brugerdefinerede kolonner er blevet opdateret. Genstart applikationen for at aktivere.");
			_dictionary.Add("SetDynamic", "Sæt dynamisk");
			_dictionary.Add("DynamicDateTimeHelp", "Brug \"dd\" for nuværende dato og tid.\r\nBrug \"led\" for sidste hændelsesdato.\r\n\r\nEksempel (sidste syv dage fra nuværende dato og tid):\r\ndd - 7\r\n\r\nEksempel (sidste syv dage fra sidste hændelsesdato):\r\nled - 7\r\n\r\nTilladte operatorer er: \"-\" og \"+\".");
			_dictionary.Add("WrongDynamicDateTimeValue", "Den dynamiske værdi for \"{0}\" er ikke korrekt angivet.");
			_dictionary.Add("Period", "Periode:");
			_dictionary.Add("TotalEvents", "Baseret på {0} hændelser");
			_dictionary.Add("EnableQuickSearch", "Aktiver hurtigsøgning");
			_dictionary.Add("CanNotDeleteSystemObject", "Den valgte søgning er et systemobjekt og kan ikke slettes.");
			_dictionary.Add("CanNotOverwriteSystemObject", "Den valgte søgning er et systemobjekt og kan ikke overskrives.");
			_dictionary.Add("DeletePasswordNoAccess", "Bruger har ikke adgang til at slette det gemte password.\r\n\r\nBruger skal have redigeringsrettigheder til HKLM i RegEdit.");
			_dictionary.Add("DeleteSearchNoAccess", "Bruger har ikke adgang til at slette den gemte søgningen.\r\n\r\nBruger skal have redigeringsrettigheder til HKLM i RegEdit.");
			_dictionary.Add("ModifyDefaultSearchNoAccess", "Bruger har ikke adgang til at modificere standardsøgningen.\r\n\r\nBruger skal have redigeringsrettigheder til HKLM i RegEdit.");
			_dictionary.Add("SaveSearchNoAccess", "Bruger har ikke adgang til at gemme søgningen.\r\n\r\nBruger skal have redigeringsrettigheder til HKLM i RegEdit.");
			_dictionary.Add("enableColumnStoreIndex", "Opretter Column Store indeks...");
			_dictionary.Add("PeriodTitle", "Periode");
			_dictionary.Add("PeriodeToolTip", "Dage: {0}\r\nTimer: {1}\r\nMinutter: {2}\r\nSekunder: {3}\r\nMillisekunder: {4}");
		}
	}
}
